# Module manifest for module 'MT_Utility'
# Generated by: Muhab T
# Generated on: 2022-08-19
@{
    #Script module or binary module file associated with this manifest.
    RootModule    = 'MT_Utility'
    #Version number of this module.
    ModuleVersion = '1.0.0'
    #Author of this module
    Author        = 'Muhab Tomoum'
    Description   = 'Multipurpose utility functions.'
}